CONTIKI_PROJECT = exercise3
all: $(CONTIKI_PROJECT)
upload: $(CONTIKI_PROJECT).upload

TARGET=nrf52840
BOARD=bluebite

CONTIKI = ../../contiki-ng

MODULES += $(CONTIKI_NG_APP_LAYER_DIR)/gatt

MAKE_NET      = MAKE_NET_NULLNET
MAKE_ROUTING  = MAKE_ROUTING_NULLROUTING
MAKE_MAC 	  = MAKE_MAC_NULLMAC

WITH_PACKETCRAFT = 1
INIT_PERIPHERAL  = 1
INIT_OBSERVER    = 1

TARGET_LIBFILES += -lm

PROJECT_SOURCEFILES += scanreport_buffer.c

include $(CONTIKI)/Makefile.include